require('dotenv').config()

export enum Games {
  CUBE = 'cube',
  TRAIN = 'train',
  MERGE = 'merge',
  TWERK = 'twerk',
  POLY = 'poly',
  TRIM = 'trim',
  ZOO = 'zoo',
  TILE = 'tile',
  FLUFF = 'fluff',
  STONE = 'stone',
  BOUNC = 'bounc',
  HIDE = 'hide',
  COUNT = 'count',
  PIN = 'pin',
  FRONTIER = 'frontier',
  AMONG = 'among',
  FACTORY = 'factory',
  SNAKE = 'snake',
  COOKING = 'cooking',
  TOWER = 'tower',
  ALL = 'all',
}

type Game = {
  id: Games,
  name: string,
  app_token?: string,
  promo_id?: string,
  delay?: number,
  iterations?: number,
}

export const games:Game[] = [
  {
    id: Games.CUBE,
    name: 'Chain Cube',
    app_token: process.env.APP_TOKEN_CUBE,
    promo_id: process.env.PROMO_ID_CUBE,
    delay: +process.env.EVENTS_DELAY_CUBE,
    iterations: +process.env.AMOUNT_ITTERATIONS_CUBE,
  },
  {
    id: Games.TRAIN,
    name: 'Train Miner',
    app_token: process.env.APP_TOKEN_TRAIN,
    promo_id: process.env.PROMO_ID_TRAIN,
    delay: +process.env.EVENTS_DELAY_TRAIN,
    iterations: +process.env.AMOUNT_ITTERATIONS_TRAIN,
  },
  {
    id: Games.MERGE,
    name: 'Merge Away',
    app_token: process.env.APP_TOKEN_MERGE,
    promo_id: process.env.PROMO_ID_MERGE,
    delay: +process.env.EVENTS_DELAY_MERGE,
    iterations: +process.env.AMOUNT_ITTERATIONS_MERGE,
  },
  {
    id: Games.POLY,
    name: 'Polysphere',
    app_token: process.env.APP_TOKEN_POLY,
    promo_id: process.env.PROMO_ID_POLY,
    delay: +process.env.EVENTS_DELAY_POLY,
    iterations: +process.env.AMOUNT_ITTERATIONS_POLY,
  },
  {
    id: Games.ZOO,
    name: 'Zoopolis',
    app_token: process.env.APP_TOKEN_ZOO,
    promo_id: process.env.PROMO_ID_ZOO,
    delay: +process.env.EVENTS_DELAY_ZOO,
    iterations: +process.env.AMOUNT_ITTERATIONS_ZOO,
  },
  {
    id: Games.STONE,
    name: 'Stone Age',
    app_token: process.env.APP_TOKEN_STONE,
    promo_id: process.env.PROMO_ID_STONE,
    delay: +process.env.EVENTS_DELAY_STONE,
    iterations: +process.env.AMOUNT_ITTERATIONS_STONE,
  },
  {
    id: Games.BOUNC,
    name: 'Bouncemasters',
    app_token: process.env.APP_TOKEN_BOUNC,
    promo_id: process.env.PROMO_ID_BOUNC,
    delay: +process.env.EVENTS_DELAY_BOUNC,
    iterations: +process.env.AMOUNT_ITTERATIONS_BOUNC,
  },
  {
    id: Games.HIDE,
    name: 'Hide Ball',
    app_token: process.env.APP_TOKEN_HIDE,
    promo_id: process.env.PROMO_ID_HIDE,
    delay: +process.env.EVENTS_DELAY_HIDE,
    iterations: +process.env.AMOUNT_ITTERATIONS_HIDE,
  },
  {
    id: Games.COUNT,
    name: 'Count Masters',
    app_token: process.env.APP_TOKEN_COUNT,
    promo_id: process.env.PROMO_ID_COUNT,
    delay: +process.env.EVENTS_DELAY_COUNT,
    iterations: +process.env.AMOUNT_ITTERATIONS_COUNT,
  },
  {
    id: Games.FRONTIER,
    name: 'Infected Frontier',
    app_token: process.env.APP_TOKEN_FRONTIER,
    promo_id: process.env.PROMO_ID_FRONTIER,
    delay: +process.env.EVENTS_DELAY_FRONTIER,
    iterations: +process.env.AMOUNT_ITTERATIONS_FRONTIER,
  },
  {
    id: Games.FACTORY,
    name: 'Factory World',
    app_token: process.env.APP_TOKEN_FACTORY,
    promo_id: process.env.PROMO_ID_FACTORY,
    delay: +process.env.EVENTS_DELAY_FACTORY,
    iterations: +process.env.AMOUNT_ITTERATIONS_FACTORY,
  },
  {
    id: Games.COOKING,
    name: 'Cooking Stories',
    app_token: process.env.APP_TOKEN_COOKING,
    promo_id: process.env.PROMO_ID_COOKING,
    delay: +process.env.EVENTS_DELAY_COOKING,
    iterations: +process.env.AMOUNT_ITTERATIONS_COOKING,
  },
  {
    id: Games.SNAKE,
    name: 'Snake Run',
    app_token: process.env.APP_TOKEN_SNAKE,
    promo_id: process.env.PROMO_ID_SNAKE,
    delay: +process.env.EVENTS_DELAY_SNAKE,
    iterations: +process.env.AMOUNT_ITTERATIONS_SNAKE,
  },
  {
    id: Games.TOWER,
    name: 'Tower Defence',
    app_token: process.env.APP_TOKEN_TOWER,
    promo_id: process.env.PROMO_ID_TOWER,
    delay: +process.env.EVENTS_DELAY_TOWER,
    iterations: +process.env.AMOUNT_ITTERATIONS_TOWER,
  },
]

export const gamesAll: Game = {
  id: Games.ALL,
  name: 'Все игры',
}